config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config.settings import production

urlpatterns = [
    path('', include('src.apps.main.urls')),
    path('pdf-processing/', include('src.apps.pdf_processing.urls', namespace='pdf')),
    # path('image-processing/', include('src.apps.image_processing.urls', namespace='image')),
    path('admin/', admin.site.urls),
]

if production.DEBUG:
    urlpatterns += static(production.MEDIA_URL, document_root=production.MEDIA_ROOT)

src/apps/pdf_processing/urls.py
from django.urls import path

from src.apps.pdf_processing import views

app_name = 'pdf'

urlpatterns = [
    # path('test/', views.TestView.as_view(), name='test'),
    path('editor/', views.PdfEditorView.as_view(), name='editor'),
    path('rotate/', views.PdfRotateView.as_view(), name='rotate'),
    path('split/', views.PdfSplitView.as_view(), name='split'),
    path('encrypt/', views.PdfEncryptView.as_view(), name='encrypt'),
    path('decrypt/', views.PdfDecryptView.as_view(), name='decrypt'),
    # path('compress/', views.PdfCompressView.as_view(), name='compress'),
    path('img-to-pdf/', views.ImgToPdfView.as_view(), name='img_to_pdf'),
    path('text-extract/', views.PdfTextExtractView.as_view(), name='text_extract'),
    path('delete-pages/', views.PdfDeletePagesView.as_view(), name='delete_pages'),
    path('add-page-numbers/', views.PdfAddPageNumbersView.as_view(), name='add_page_numbers'),
]

src/image_processing/urls.py
from django.urls import path

from src.image_processing import views

app_name = 'image'

urlpatterns = [
    path('', views.ImageProcessingView.as_view(), name='image_processing'),
]

src/main/urls.py
from django.urls import path

from src.main import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
]

src/pdf_processing/urls.py
from django.urls import path

from src.pdf_processing import views

app_name = 'pdf'

urlpatterns = [
    path('protect/', views.PdfProtectView.as_view(), name='protect'),
    path('text-extract/', views.PdfTextExtractView.as_view(), name='text_extract'),
    path('download-result/<str:file_id>/', views.DownloadResultView.as_view(), name='download_result')
]

src/apps/image_processing/models.py
from django.db import models

# Create your models here.

src/apps/main/models.py
from django.db import models

# Create your models here.

src/apps/notifications/models.py
from django.db import models

# Create your models here.

src/apps/pdf_processing/models.py
import uuid

from django.db import models


class File(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    file = models.FileField(upload_to='pdf_processing/')
    time_add = models.DateTimeField(auto_now_add=True)

src/apps/main/forms.py
from django import forms


class QrCodeForm(forms.Form):
    text_data = forms.CharField(
        max_length=200,
        label='Дані',
        help_text="Введіть посилання на веб-сайт, текстові дані і т. п."
    )

src/apps/image_processing/views.py
from django.views.generic import TemplateView


class ImageProcessingView(TemplateView):
    template_name = 'image_processing.html'

src/apps/main/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

# class QrCodeGenerationView(FormView):
#     template_name = 'qrcode.html'
#     form_class = QrCodeForm
#
#     def form_valid(self, form):
#         qrcode = services.generate_qrcode(form.cleaned_data['text_data'])
#         return self.render_to_response(self.get_context_data(qrcode=services.image_to_base64(qrcode, 'JPEG')))
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['qrcode'] = kwargs.get('qrcode')
#         return context

src/apps/notifications/views.py
from django.shortcuts import render

# Create your views here.

src/apps/pdf_processing/views.py
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, TemplateView

from src.apps.pdf_processing import services
from src.apps.pdf_processing import tasks
from src.apps.pdf_processing import forms
from src.apps.pdf_processing.models import File


@method_decorator(csrf_exempt, name='dispatch')
class PdfTextExtractView(FormView):
    form_class = forms.PDFFileUploadForm
    template_name = 'pdf_processing/pdf_text_extract.html'

    def form_valid(self, form):
        file_obj = File.objects.create(file=form.cleaned_data['file'])
        tasks.extract_text_from_pdf.delay(services.full_path(
            file_obj.file.path),
            str(file_obj.id),
            form.cleaned_data.get('password', ''),
        )
        return JsonResponse({'message': 'success', 'file_id': file_obj.id})

    def form_invalid(self, form):
        return JsonResponse({'message': 'error'})


@method_decorator(csrf_exempt, name='dispatch')
class PdfEncryptView(FormView):
    form_class = forms.PDFFileEncryptForm
    template_name = 'pdf_processing/pdf_encrypt.html'

    def form_valid(self, form):
        file_obj = File.objects.create(file=form.cleaned_data['file'])
        tasks.pdf_encrypt.delay(services.full_path(
            file_obj.file.path),
            str(file_obj.id),
            form.cleaned_data.get('password', ''),
            form.cleaned_data.get('new_password')
        )
        return JsonResponse({'message': 'success', 'file_id': file_obj.id})

    def form_invalid(self, form):
        return JsonResponse({'message': 'error'})


@method_decorator(csrf_exempt, name='dispatch')
class PdfDecryptView(FormView):
    form_class = forms.PDFFileDecryptForm
    template_name = 'pdf_processing/pdf_decrypt.html'

    def form_valid(self, form):
        file_obj = File.objects.create(file=form.cleaned_data['file'])
        tasks.pdf_decrypt.delay(services.full_path(file_obj.file.path), str(file_obj.id), form.cleaned_data['password'])
        return JsonResponse({'message': 'success', 'file_id': file_obj.id})

    def form_invalid(self, form):
        return JsonResponse({'message': 'error'})


class PdfCompressView(FormView):
    form_class = forms.PDFFileUploadForm
    template_name = 'pdf_processing/file_upload.html'

    def form_valid(self, form):
        file_obj = File.objects.create(file=form.cleaned_data['file'])
        tasks.pdf_compress.delay(services.full_path(file_obj.file.path), str(file_obj.id))
        return JsonResponse({'message': 'success', 'file_id': file_obj.id})

    def form_invalid(self, form):
        return JsonResponse({'message': 'error'})


@method_decorator(csrf_exempt, name='dispatch')
class PdfSplitView(TemplateView):
    template_name = 'pdf_processing/pdf_split.html'

    def post(self, request, *args, **kwargs):
        form = forms.PDFFileSplitForm(request.POST, request.FILES)
        if form.is_valid():
            file_obj = File.objects.create(file=form.cleaned_data['file'])
            tasks.pdf_split.delay(
                file_path=services.full_path(file_obj.file.path),
                file_id=str(file_obj.id),
                selected_pages=form.cleaned_data.get('selected_pages', []),
                save_separate=form.cleaned_data.get('save_separate', False),
                password=form.cleaned_data.get('password', ''),
            )
            return JsonResponse({'message': 'success', 'file_id': file_obj.id})
        else:
            return JsonResponse({'message': 'error'})


@method_decorator(csrf_exempt, name='dispatch')
class PdfAddPageNumbersView(TemplateView):
    template_name = 'pdf_processing/pdf_addpagenumbers.html'

    def post(self, request, *args, **kwargs):
        form = forms.PDFFileAddPageNumbersForm(request.POST, request.FILES)
        if form.is_valid():
            file_obj = File.objects.create(file=form.cleaned_data['file'])
            tasks.pdf_addpagenumbers.delay(
                file_path=services.full_path(file_obj.file.path),
                file_id=str(file_obj.id),
                password=form.cleaned_data.get('password', ''),
                number_on_first_page=form.cleaned_data.get('number_on_first_page', False),
                number_position=form.cleaned_data.get('number_position', 'c-bottom')
            )
            return JsonResponse({'message': 'success', 'file_id': file_obj.id})
        else:
            return JsonResponse({'message': 'error'})


@method_decorator(csrf_exempt, name='dispatch')
class PdfRotateView(TemplateView):
    template_name = 'pdf_processing/pdf_rotate.html'

    def post(self, request, *args, **kwargs):
        form = forms.PDFFileRotateForm(request.POST, request.FILES)
        print(request.POST)
        if form.is_valid():
            file_obj = File.objects.create(file=form.cleaned_data['file'])
            tasks.pdf_rotate.delay(
                file_path=services.full_path(file_obj.file.path),
                file_id=str(file_obj.id),
                password=form.cleaned_data.get('password', ''),
                document_rotation=form.cleaned_data.get('document_rotation', 0),
                pages_rotation=form.cleaned_data.get('pages_rotation', {})
            )
            return JsonResponse({'message': 'success', 'file_id': file_obj.id})
        else:
            return JsonResponse({'message': 'error'})


@method_decorator(csrf_exempt, name='dispatch')
class ImgToPdfView(TemplateView):
    template_name = 'pdf_processing/img_to_pdf.html'

    def post(self, request, *args, **kwargs):
        form = forms.ImgToPDFForm(request.POST, request.FILES)
        if form.is_valid():
            images = form.cleaned_data["images"]

            file_id = ''
            files_path = []
            for i, img in enumerate(images):
                file_obj = File.objects.create(file=img)
                files_path.append(services.full_path(file_obj.file.path))
                if i == 0:
                    file_id = file_obj.id

            tasks.img_to_pdf.delay(
                files_path=files_path,
                file_id=str(file_id),
                images_rotation=form.cleaned_data.get('images_rotation', []),
                orientation=form.cleaned_data.get('orientation', 'Auto orientation'),
                size=form.cleaned_data.get('size', 'A4')
            )

            return JsonResponse({'message': 'success', 'file_id': file_id})
        else:
            return JsonResponse({'message': 'error'})


@method_decorator(csrf_exempt, name='dispatch')
class PdfDeletePagesView(TemplateView):
    template_name = 'pdf_processing/pdf_delete_pages.html'

    def post(self, request, *args, **kwargs):
        form = forms.PDFDeletePagesForm(request.POST, request.FILES)
        if form.is_valid():
            file_obj = File.objects.create(file=form.cleaned_data['file'])
            tasks.pdf_delete_pages.delay(
                file_path=services.full_path(file_obj.file.path),
                file_id=str(file_obj.id),
                password=form.cleaned_data.get('password', ''),
                pages_to_delete=form.cleaned_data.get('selected_pages')
            )
            return JsonResponse({'message': 'success', 'file_id': file_obj.id})
        else:
            return JsonResponse({'message': 'error'})


class PdfEditorView(TemplateView):
    template_name = 'pdf_processing/pdf_editor.html'


class TestView(FormView):
    form_class = forms.TestForm
    template_name = 'pdf_processing/test.html'

    def post(self, request, *args, **kwargs):
        form = forms.TestForm(request.POST, request.FILES)
        print(form.is_valid())
        print(request.FILES, request.POST)
        return JsonResponse({'message': 'error'})

src/pdf_processing/views.py
from django.http import JsonResponse, FileResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import FormView, TemplateView

from src.pdf_processing import services, tasks
from src.pdf_processing.forms import PDFFileUploadForm, PDFFileProtectForm
from src.pdf_processing.models import File


class DownloadResultView(TemplateView):
    template_name = 'pdf_processing/download_result.html'

    def get(self, request, *args, **kwargs):
        get_object_or_404(File, id=self.kwargs['file_id'])
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['file_id'] = self.kwargs.get('file_id')
        return context


class PdfTextExtractView(FormView):
    form_class = PDFFileUploadForm
    template_name = 'pdf_processing/pdf_processing.html'

    def form_valid(self, form):
        file_obj = File.objects.create(file=form.cleaned_data['file'])
        tasks.extract_text_from_pdf.delay(services.full_path(file_obj.file.path), str(file_obj.id))
        return HttpResponseRedirect(reverse('pdf:download_result', kwargs={'file_id': file_obj.id}))
        # text = services.extract_text_from_pdf(form.cleaned_data['file'])
        # headers = {'Content-Disposition': 'attachment; filename="text_from_pdf.txt"'}
        # return FileResponse(
        #     text,
        #     content_type='text/plain',
        #     headers=headers
        # )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Витягти текст із pdf'
        context['form_btn_text'] = 'Витягти текст'
        return context


class PdfProtectView(FormView):
    form_class = PDFFileProtectForm
    template_name = 'pdf_processing/pdf_processing.html'

    def form_invalid(self, form):
        return JsonResponse({'message': 'Некорректний pdf файл'})

    def form_valid(self, form):
        protected_pdf_file = services.pdf_protect(form.cleaned_data['file'], form.cleaned_data['password'])
        return FileResponse(
            protected_pdf_file,
            as_attachment=True,
            filename='protected_pdf.pdf',
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Захистити pdf'
        context['form_btn_text'] = 'Створити пароль для вибраного файлу'
        return context

# class TestView(FormView):
#     form_class = PDFFileUploadForm
#     template_name = 'pdf_processing/pdf_processing.html'
#     success_url = 'home'
#
#     def form_valid(self, form):
#         time.sleep(100)
#         super().form_valid()

src/templates/image_processing.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <head>
        <link rel="stylesheet" href="{% static 'css/image_processing/style.css' %}">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script>
            jQuery.fn.outerHTML = function () {
                return jQuery('<div />').append(this.eq(0).clone()).html();
            };
            Number.prototype.countDecimals = function () {
                if (Math.floor(this.valueOf()) === this.valueOf()) return 0;
                return this.toString().split(".")[1].length || 0;
            }
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.6.3/fabric.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/spectrum-colorpicker2/dist/spectrum.min.js"></script>
        <link rel="stylesheet" type="text/css"
              href="https://cdn.jsdelivr.net/npm/spectrum-colorpicker2/dist/spectrum.min.css">

        <script src="{% static 'js/image_processing/grapick.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/image_processing/grapick.min.css' %}">

        <script src="{% static 'js/image_processing/undo-redo-stack.js' %}"></script>

        <script src="{% static 'js/image_processing/core.js' %}"></script>
        <script src="{% static 'js/image_processing/toolbar.js' %}"></script>
        <script src="{% static 'js/image_processing/canvas.js' %}"></script>
        <script src="{% static 'js/image_processing/shapes.js' %}"></script>

        <script src="{% static 'js/image_processing/freeDrawSettings.js' %}"></script>
        <script src="{% static 'js/image_processing/canvasSettings.js' %}"></script>
        <script src="{% static 'js/image_processing/selectionSettings.js' %}"></script>

        <script src="{% static 'js/image_processing/drawingLine.js' %}"></script>
        <script src="{% static 'js/image_processing/drawingPath.js' %}"></script>
        <script src="{% static 'js/image_processing/drawingText.js' %}"></script>
        <script src="{% static 'js/image_processing/tip.js' %}"></script>
        <script src="{% static 'js/image_processing/upload.js' %}"></script>
        <script src="{% static 'js/image_processing/copyPaste.js' %}"></script>

        <script src="{% static 'js/image_processing/utils.js' %}"></script>
        <script src="{% static 'js/image_processing/zoom.js' %}"></script>
        <script src="{% static 'js/image_processing/saveInBrowser.js' %}"></script>

    </head>
{% endblock head %}
{% block content %}
    <div class="tool_wrapper">
        <div id="image-editor-container"></div>
    </div>
{% endblock content %}
{% block js %}
    <script src="{% static 'js/image_processing/script.js' %}"></script>
{% endblock js %}

src/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block header_bottom %}
    <div class="intro">
        <div class="container">
            <div class="intro-inner">
                <div>
                    <h2 class="intro-title">Web tools by AnyToolLab:)</h2>
                    <p class="intro-description">Find the exact tool you need!</p>
                </div>
                <div class="slogan-wrapper">
                    <h3 class="slogan">Taking care of You</h3>
                    <div class="slogan-img"></div>
                </div>
                <span class="line"></span>
            </div>
        </div>
    </div>
{% endblock header_bottom %}
{% block content %}
    <section class="tools-section">
        <h2 class="hidden">Tools</h2>
        <section class="tool_type-section">
            <div class="container">
                <div class="tool_type-section-inner">
                    <h2 class="tool_type-section-title">
                        PDF Tools
                    </h2>
                    <div class="tool_type-tools">
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:editor' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/pdf_edit.png' %}" alt="Tool icon" class="ttt-img">
                                    <h3 class="ttt-title">Edit<span class="hidden">pdf</span></h3>
                                </div>
                            </a>
                        </div>
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:split' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/pdf_split.png' %}" alt="Tool icon" class="ttt-img">
                                    <h3 class="ttt-title">Split<span class="hidden">pdf</span></h3>
                                </div>
                            </a>
                        </div>
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:encrypt' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/pdf_protect.png' %}" alt="Tool icon" class="ttt-img">
                                    <h3 class="ttt-title">Protect<span class="hidden">pdf</span></h3>
                                </div>
                            </a>
                        </div>
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:decrypt' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/pdf_unlock.png' %}" alt="Tool icon" class="ttt-img">
                                    <h3 class="ttt-title">Unlock<span class="hidden">pdf</span></h3>
                                </div>
                            </a>
                        </div>
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:add_page_numbers' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/pdf_page_number.png' %}" alt="Tool icon"
                                         class="ttt-img">
                                    <h3 class="ttt-title">Add page numbers<span class="hidden">pdf</span></h3>
                                </div>
                            </a>
                        </div>
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:text_extract' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/pdf_extract_text.png' %}" alt="Tool icon"
                                         class="ttt-img">
                                    <h3 class="ttt-title">Extract text<span class="hidden">pdf</span></h3>
                                </div>
                            </a>
                        </div>
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:delete_pages' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/pdf_delete_pages.png' %}" alt="Tool icon"
                                         class="ttt-img">
                                    <h3 class="ttt-title">Delete pages<span class="hidden">pdf</span></h3>
                                </div>
                            </a>
                        </div>
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:img_to_pdf' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/img2pdf.png' %}" alt="Tool icon" class="ttt-img">
                                    <h3 class="ttt-title">PNG to PDF</h3>
                                </div>
                            </a>
                        </div>
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:img_to_pdf' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/img2pdf.png' %}" alt="Tool icon" class="ttt-img">
                                    <h3 class="ttt-title">JPG to PDF</h3>
                                </div>
                            </a>
                        </div>
                        <div class="tool_type-tool">
                            <a href="{% url 'pdf:rotate' %}" class="ttt-link">
                                <div class="tool_type-tool-inner">
                                    <img src="{% static 'images/pdf_rotate.png' %}" alt="Tool icon" class="ttt-img">
                                    <h3 class="ttt-title">Rotate<span class="hidden">pdf</span></h3>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock content %}